version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: "rrm-admin"
        ports:
            - 9000:80
        volumes:
            - ./:/var/www/html
    pgsql:
        image: postgres:12.0-alpine
        restart: always
        container_name: rrm-admin-pgsql
        working_dir: /data/pgsql
        volumes:
            - ./postgresql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: rrm-admin
        ports:
            - 9001:5432
