version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: "rrm-admin"
        ports:
            - 9000:80
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "9001:3306"
        environment:
            MYSQL_DATABASE: "rrm_db"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./db:/var/lib/mysql
